apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: sample-deployment
        image: nash20/edc_ci_image:5
        ports:  # Correct indentation
        - containerPort: 81
      imagePullSecrets:
      - name: docker-registry-secret
      
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 81
    nodePort: 31107     
