apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pull-app
  template:
    metadata:
      labels:
        app: pull-app
    spec:
      containers:
      - name: pull-deploy
        image: nash20/edc_ci_image:54
        ports:
        - containerPort: 8083
      imagePullSecrets:
      - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: pull-ser
spec:
  selector:
    app: pull-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8083
    nodePort: 31104
