apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust
  template:
    metadata:
      labels:
        app: rust
    spec:
      containers:
      - name: rust
        image: nash20/edc_ci_image:54
        ports:
        - containerPort: 8083
      imagePullSecrets:
      - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: rust-service
spec:
  selector:
    app: rust
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 31103 
  type: NodePort
  sessionAffinity: None 
  externalTrafficPolicy: Cluster
