---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-jenkins-pod
  labels:
    app: webserver-ci
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: webserver-ci
spec:
  selector:
    app: webserver-ci
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Use 'NodePort' if LoadBalancer is not available
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: webserver-ci
spec:
  selector:
    app: webserver-ci
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 50000
    targetPort: 50000
  type: LoadBalancer  # Use 'NodePort' if LoadBalancer is not available
